
country_codes_dict = {
    'Bolivia (Plurinational State of)': 'BOL',
    'Democratic Republic of the Congo': 'COD',
    'Iran (Islamic Republic of)': 'IRN',
    'Micronesia (Federated States of)': 'FSM',
    'Palestine': 'PSE',
    'Republic of Korea': 'KOR',
    'Republic of Niue': 'NIU',
    'Taiwan (Province of China)': 'TWN',
    'The former Yugoslav Republic of Macedonia': 'MKD',
    'Turkey': 'TUR',
    'United States Virgin Islands': 'VIR',
    'Venezuela (Bolivarian Republic of)': 'VEN',
    'Bolivarian Republic of Venezuela': 'VEN',
    'Commonwealth of the Bahamas': 'BHS',
    'Czech Republic': 'CZE',
    "Democratic People's Republic of Korea": 'PRK',
    'Federated States of Micronesia': 'FSM',
    'Islamic Republic of Iran': 'IRN',
    'Kingdom of Eswatini': 'SWZ',
    'Plurinational State of Bolivia': 'BOL',
    'Principality of Monaco': 'MCO',
    'Republic of Cabo Verde': 'CPV',
    "Republic of Côte d'Ivoire": 'CIV',
    'Republic of Moldova': 'MDA',
    'Republic of Nauru': 'NRU',
    'Republic of Palau': 'PLW',
    'Republic of San Marino': 'SMR',
    'Republic of the Gambia': 'GMB',
    'Socialist Republic of Viet Nam': 'VNM',
    'United Kingdom of Great Britain and Northern Ireland': 'GBR',
    'United Republic of Tanzania': 'TZA',
    'United States of America': 'USA',
    'Republic of the Philippines': 'PHL',
    'Republic of the Union of Myanmar': 'MMR',
    'Republic of Maldives': 'MDV',
    'Republic of Indonesia': 'IDN',
    'Kingdom of Tonga': 'TON',
    'Republic of Vanuatu': 'VUT',
    "People's Republic of China": 'CHN',
    'Kingdom of Cambodia': 'KHM',
    'Independent State of Samoa': 'WSM',
    'Independent State of Papua New Guinea': 'PNG',
    'Republic of Kiribati': 'KIR',
    'Republic of Fiji': 'FJI',
    'Republic of the Marshall Islands': 'MHL',
    'Republic of Tajikistan': 'TJK',
    'Democratic Republic of Timor-Leste': 'TLS',
    'Republic of Kazakhstan': 'KAZ',
    'Republic of Bulgaria': 'BGR',
    'Kingdom of Thailand': 'THA',
    'Republic of Croatia': 'HRV',
    'Republic of Albania': 'ALB',
    'Kyrgyz Republic': 'KGZ',
    'Republic of Uzbekistan': 'UZB',
    'Republic of Azerbaijan': 'AZE',
    'Democratic Socialist Republic of Sri Lanka': 'LKA',
    'Republic of Armenia': 'ARM',
    'Republic of Lithuania': 'LTU',
    'Republic of Estonia': 'EST',
    'Republic of Belarus': 'BLR',
    'Republic of Latvia': 'LVA',
    'Republic of Slovenia': 'SVN',
    'Principality of Andorra': 'AND',
    'Kingdom of Belgium': 'BEL',
    'Slovak Republic': 'SVK',
    'Republic of Austria': 'AUT',
    'Republic of Finland': 'FIN',
    'Republic of Serbia': 'SRB',
    'Kingdom of Denmark': 'DNK',
    'Republic of Cyprus': 'CYP',
    'French Republic': 'FRA',
    'Republic of Poland': 'POL',
    'Republic of Singapore': 'SGP',
    'Swiss Confederation': 'CHE',
    'Kingdom of Spain': 'ESP',
    'Kingdom of Sweden': 'SWE',
    'Portuguese Republic': 'PRT',
    'Kingdom of Norway': 'NOR',
    'Kingdom of the Netherlands': 'NLD',
    'Grand Duchy of Luxembourg': 'LUX',
    'Republic of Malta': 'MLT',
    'Republic of Italy': 'ITA',
    'State of Israel': 'ISR',
    'Hellenic Republic': 'GRC',
    'Republic of Iceland': 'ISL',
    'Federal Republic of Germany': 'DEU',
    'Republic of Cuba': 'CUB',
    'Commonwealth of Dominica': 'DMA',
    'Argentine Republic': 'ARG',
    'Republic of Chile': 'CHL',
    'Eastern Republic of Uruguay': 'URY',
    'Republic of Peru': 'PER',
    'Republic of Ecuador': 'ECU',
    'Republic of Suriname': 'SUR',
    'Republic of Trinidad and Tobago': 'TTO',
    'Republic of Guatemala': 'GTM',
    'Republic of Costa Rica': 'CRI',
    'Republic of El Salvador': 'SLV',
    'Republic of Guyana': 'GUY',
    'Republic of Colombia': 'COL',
    'Republic of Haiti': 'HTI',
    'Hashemite Kingdom of Jordan': 'JOR',
    'Republic of Iraq': 'IRQ',
    'Kingdom of Bahrain': 'BHR',
    "People's Democratic Republic of Algeria": 'DZA',
    'Arab Republic of Egypt': 'EGY',
    'Republic of Paraguay': 'PRY',
    'Federative Republic of Brazil': 'BRA',
    'Republic of Panama': 'PAN',
    'United Mexican States': 'MEX',
    'Republic of Nicaragua': 'NIC',
    'Islamic Republic of Afghanistan': 'AFG',
    'Republic of Yemen': 'YEM',
    'Republic of Turkey': 'TUR',
    'Republic of Tunisia': 'TUN',
    'Republic of Honduras': 'HND',
    'State of Qatar': 'QAT',
    'Kingdom of Saudi Arabia': 'SAU',
    'State of Kuwait': 'KWT',
    'Sultanate of Oman': 'OMN',
    'Kingdom of Morocco': 'MAR',
    'State of Libya': 'LBY',
    'Lebanese Republic': 'LBN',
    'Union of the Comoros': 'COM',
    'Republic of Burundi': 'BDI',
    'Islamic Republic of Pakistan': 'PAK',
    'Federal Democratic Republic of Nepal': 'NPL',
    'Republic of India': 'IND',
    "People's Republic of Bangladesh": 'BGD',
    'Republic of Madagascar': 'MDG',
    'Republic of Guinea-Bissau': 'GNB',
    'Republic of Sudan': 'SDN',
    'State of Eritrea': 'ERI',
    'Kingdom of Bhutan': 'BTN',
    'Gabonese Republic': 'GAB',
    'Republic of Botswana': 'BWA',
    'Republic of South Africa': 'ZAF',
    'Republic of Chad': 'TCD',
    'Republic of Kenya': 'KEN',
    'Republic of Cameroon': 'CMR',
    'Republic of Benin': 'BEN',
    'Kingdom of Lesotho': 'LSO',
    'Republic of Ghana': 'GHA',
    'Republic of the Niger': 'NER',
    'Republic of Equatorial Guinea': 'GNQ',
    'Federal Democratic Republic of Ethiopia': 'ETH',
    'Democratic Republic of Sao Tome and Principe': 'STP',
    'Republic of Djibouti': 'DJI',
    'Republic of Zambia': 'ZMB',
    'Republic of Liberia': 'LBR',
    'Republic of the Congo': 'COG',
    'Republic of Mali': 'MLI',
    'Islamic Republic of Mauritania': 'MRT',
    'Republic of Angola': 'AGO',
    'Republic of Mauritius': 'MUS',
    'Republic of Rwanda': 'RWA',
    'Republic of Uganda': 'UGA',
    'Federal Republic of Somalia': 'SOM',
    'Republic of Mozambique': 'MOZ',
    'Republic of Malawi': 'MWI',
    'Republic of Seychelles': 'SYC',
    'Republic of Namibia': 'NAM',
    'Togolese Republic': 'TGO',
    'Republic of Zimbabwe': 'ZWE',
    'Republic of Guinea': 'GIN',
    'Republic of Senegal': 'SEN',
    'Federal Republic of Nigeria': 'NGA',
    'Republic of Sierra Leone': 'SLE',
    'Republic of South Sudan': 'SSD',
    'Democratic Republic Of The Congo': 'COD',
    'Republic Of Italy': 'ITA',
    'Republic Of Korea': 'KOR',
    'Republic Of Niue': 'NIU',
    'Republic Of Rwanda': 'RWA',
    'Republic Of Sudan': 'SDN',
    'Republic Of Turkey': 'TUR',
    'Republic Of The Union Of Myanmar': 'MMR',
    'State Of Eritrea': 'ERI',
    'State Of Libya': 'LBY',
    'Taiwan (Province Of China)': 'TWN',
    'The Former Yugoslav Republic Of Macedonia': 'MKD'
}
